name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  docker_build_push_amd64:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1 
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.PAT }}
      - name: Build and push client Docker image
        uses: docker/build-push-action@v2
        with:
          context: ./client
          push: true
          tags: ghcr.io/${{ github.repository }}/client:latest-amd64
          platforms: linux/amd64
      - name: Build and push server (python) Docker image
        uses: docker/build-push-action@v2
        with:
          context: ./server/python
          push: true
          tags: ghcr.io/${{ github.repository }}/server:latest-amd64-python
          platforms: linux/amd64
      - name: Build and push server (go) Docker image
        uses: docker/build-push-action@v2
        with:
          context: ./server/go
          push: true
          tags: ghcr.io/${{ github.repository }}/server:latest-amd64-go
          platforms: linux/amd64

  docker_build_push_arm64:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1 
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.PAT }}
      - name: Build and push client Docker image
        uses: docker/build-push-action@v2
        with:
          context: ./client
          push: true
          tags: ghcr.io/${{ github.repository }}/client:latest-arm64
          platforms: linux/arm64/v8
      - name: Build and push server Docker image
        uses: docker/build-push-action@v2
        with:
          context: ./server/python
          push: true
          tags: ghcr.io/${{ github.repository }}/server:latest-arm64-python
          platforms: linux/arm64/v8
      - name: Build and push server Docker image
        uses: docker/build-push-action@v2
        with:
          context: ./server/go
          push: true
          tags: ghcr.io/${{ github.repository }}/server:latest-arm64-go
          platforms: linux/arm64/v8